# Generated by Django 4.2.3 on 2024-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.TextField(verbose_name='Розблокування')),
                ('price2', models.TextField(verbose_name='Хвилина поїздки')),
                ('price3', models.TextField(verbose_name='Пауза')),
                ('price4', models.TextField(verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'ContentEditor',
                'verbose_name_plural': 'ContentEditor',
            },
        ),
    ]
